name: SonarCloud
on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar_cloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: build tests
        run: |
            npm i
            npm run test:coverage
            ls -l ./reports/coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.javascript.lcov.reportPaths=./reports/coverage/lcov.info
